apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: SERVICE_NAME
serialPipeline:
  stages:
    - targetId: SERVICE_NAME-target
      profiles: [main]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: SERVICE_NAME-target
requireApproval: false
run:
  location: projects/PROJECT_ID/locations/REGION
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  serviceAccount: cnsrun-clouddeploy@PROJECT_ID.iam.gserviceaccount.com
